[versions]
agp = "8.5.2"
kotlin = "2.0.20"
composeBom = "2024.09.02"
lifecycle = "2.8.6"
datastore = "1.1.1"
coil = "2.7.0"
junit = "4.13.2"
roborazzi = "1.26.0"
androidx-test-junit = { module = "androidx.test.ext:junit", version = "1.2.1" }
robolectric = "4.13"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.9.2" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.13.1" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-tv-foundation = { module = "androidx.tv:tv-foundation", version = "1.0.0-alpha11" }
compose-tv-material = { module = "androidx.tv:tv-material", version = "1.0.0" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
junit = { module = "junit:junit", version.ref = "junit" }
roborazzi = { module = "io.github.takahirom.roborazzi:roborazzi", version.ref = "roborazzi" }
roborazzi-compose = { module = "io.github.takahirom.roborazzi:roborazzi-compose", version.ref = "roborazzi" }
androidx-test-junit = { module = "androidx.test.ext:junit", version = "1.2.1" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }
